[versions]
kotlin = "2.1.20"
fabric-loom = "1.10-SNAPSHOT"
iridium = "3.4.0"
# Dependencies
server_translations = "2.3.1+1.21-pre2"
fzzy-config = "0.7.0+1.21"
# QoL
modmenu = "11.0.3"
emi = "1.1.22+1.21.1"
# Testing
creative-works = "0.5.0"

[libraries]
# Dependencies
fzzy-config = { module = "me.fzzyhmstrs:fzzy_config", version.ref = "fzzy-config" }
server-translations-api = { module = "xyz.nucleoid:server-translations-api", version.ref = "server_translations" }
# QoL
modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
emi = { module = "dev.emi:emi-fabric", version.ref = "emi" }
# Testing
creative-works = { module = "org.teamvoided:creative_works", version.ref = "creative-works" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
fabric-loom = { id = "fabric-loom", version.ref = "fabric-loom" }
iridium = { id = "org.teamvoided.iridium", version.ref = "iridium"}
iridium-publish = { id = "iridium.project.publish-script", version.ref = "iridium"}
iridium-upload = { id = "iridium.mod.upload-script", version.ref = "iridium" }